In [ ]:
pip install tensorflow

In [105]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D

import pickle
import pandas as pd
import numpy as np

In [106]:
df = pd.DataFrame(np.random.randint(0,100, size = (100,4)), columns = list('ABCD'))

In [107]:
df.head()

A   B   C   D
0  47  17  54  90
1  95  71  84  63
2  81  25  48  35
3  75  79  14  12
4  42  91  62  41

In [108]:
mylist = [1,2,3,4,5]

In [109]:
se = pd.Series(mylist)

In [110]:
df["target"] = np.random.choice(mylist, size = len(df))

In [111]:
df.head()

A   B   C   D  target
0  47  17  54  90       5
1  95  71  84  63       4
2  81  25  48  35       5
3  75  79  14  12       1
4  42  91  62  41       2

In [15]:
import time


In [112]:
df

A   B   C   D  target
0   47  17  54  90       5
1   95  71  84  63       4
2   81  25  48  35       5
3   75  79  14  12       1
4   42  91  62  41       2
..  ..  ..  ..  ..     ...
95  50   8  62  53       1
96  46  77  85  94       2
97  23   1  53  12       5
98   5  44  39  34       2
99   9  60  61  27       1

[100 rows x 5 columns]

In [113]:
cols = list(df.columns)
cols = [cols[-1]] + cols[:-1]
df = df[cols]

In [114]:
df.head()

target   A   B   C   D
0       5  47  17  54  90
1       4  95  71  84  63
2       5  81  25  48  35
3       1  75  79  14  12
4       2  42  91  62  41

In [115]:
feature_cols = ['A', 'B', 'C', 'D']

In [116]:
X = df.loc[:, feature_cols]


In [117]:
X.shape

(100, 4)

In [118]:
y = df.target

In [119]:
y.head()

0    5
1    4
2    5
3    1
4    2
Name: target, dtype: int64

In [123]:

model = tf.keras.models.Sequential()  # a basic feed-forward model
model.add(tf.keras.layers.Flatten())  # takes our 28x28 and makes it 1x784
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))  # a simple fully-connected layer, 128 units, relu activation
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))  # a simple fully-connected layer, 128 units, relu activation
model.add(tf.keras.layers.Dense(6, activation=tf.nn.softmax))

In [124]:
model.compile(optimizer='adam',  # Good default optimizer to start with
              loss='sparse_categorical_crossentropy',  # how will we calculate our "error." Neural network aims to minimize loss.
              metrics=['accuracy'])  # what to track

In [125]:
model.fit(X, y, epochs=3)  # train the model

Epoch 1/3
4/4 [==============================] - 0s 3ms/step - loss: 8.8991 - accuracy: 0.2500
Epoch 2/3
4/4 [==============================] - 0s 1ms/step - loss: 3.7671 - accuracy: 0.2000
Epoch 3/3
4/4 [==============================] - 0s 1ms/step - loss: 3.8101 - accuracy: 0.2700


In [126]:
model.save('nlp_test.model')


INFO:tensorflow:Assets written to: nlp_test.model/assets


In [127]:
new_model = tf.keras.models.load_model('nlp_test.model')

In [128]:
X

A   B   C   D
0   47  17  54  90
1   95  71  84  63
2   81  25  48  35
3   75  79  14  12
4   42  91  62  41
..  ..  ..  ..  ..
95  50   8  62  53
96  46  77  85  94
97  23   1  53  12
98   5  44  39  34
99   9  60  61  27

[100 rows x 4 columns]

In [129]:
x_test = X.head(20)

In [130]:
x_test = X.head(20)

In [131]:
x_test = x_test.to_numpy()

In [132]:
x_test

array([[47, 17, 54, 90],
       [95, 71, 84, 63],
       [81, 25, 48, 35],
       [75, 79, 14, 12],
       [42, 91, 62, 41],
       [ 7, 83, 62, 58],
       [50,  1, 66, 31],
       [43, 36,  8, 95],
       [42, 27, 81, 95],
       [73, 13,  5, 25],
       [46, 61, 96, 27],
       [12, 96, 97, 50],
       [22, 44, 81, 63],
       [65,  0, 91, 90],
       [12, 74, 34, 48],
       [60, 77, 94, 72],
       [ 7, 42,  8, 62],
       [52, 54, 89, 26],
       [48, 82, 51,  3],
       [10, 15, 42, 73]])

In [133]:
predictions = new_model.predict(x_test)

In [151]:
predictions

array([[1.68902643e-05, 8.97302572e-03, 2.89548677e-03, 4.19625826e-02,
        8.10351670e-01, 1.35800347e-01],
       [1.42803483e-05, 4.48132958e-03, 6.02494460e-04, 5.46296798e-02,
        9.36008990e-01, 4.26325947e-03],
       [7.83943280e-04, 2.35293120e-01, 7.11715072e-02, 5.46975732e-01,
        5.79619072e-02, 8.78137425e-02],
       [3.78038891e-07, 7.66366363e-01, 3.29913193e-04, 2.13747486e-01,
        1.54992538e-02, 4.05669212e-03],
       [1.24655562e-05, 1.19096381e-04, 1.21080894e-02, 6.80591166e-02,
        8.24447751e-01, 9.52534899e-02],
       [5.42725611e-05, 2.87921692e-04, 5.61224997e-01, 3.43238637e-02,
        1.01409927e-01, 3.02699000e-01],
       [3.16483376e-04, 2.85629127e-02, 1.40342722e-02, 2.03391418e-01,
        7.35952616e-01, 1.77422892e-02],
       [3.26176905e-06, 4.01226096e-02, 6.40280321e-02, 1.04667939e-01,
        7.71102011e-01, 2.00761762e-02],
       [1.47443934e-05, 4.47248295e-03, 7.98664708e-03, 5.66514209e-02,
        6.63161576e-01, 

In [ ]:
# to get the probability

In [156]:
probs = predictions.max(1)


In [157]:
probs

array([0.81035167, 0.936009  , 0.54697573, 0.76636636, 0.82444775,
       0.561225  , 0.7359526 , 0.771102  , 0.6631616 , 0.3966821 ,
       0.7892087 , 0.4609404 , 0.45655832, 0.90602285, 0.6257935 ,
       0.7323752 , 0.5208791 , 0.80764556, 0.95217615, 0.6739844 ],
      dtype=float32)

In [154]:
preds_classes = new_model.predict_classes(x_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [155]:
preds_classes

array([4, 4, 3, 1, 4, 2, 4, 4, 4, 3, 4, 5, 4, 4, 2, 4, 4, 4, 4, 4])

In [152]:
classes = np.argmax(predictions, axis=-1)


In [153]:
classes

array([4, 4, 3, 1, 4, 2, 4, 4, 4, 3, 4, 5, 4, 4, 2, 4, 4, 4, 4, 4])

In [134]:
x_test

array([[47, 17, 54, 90],
       [95, 71, 84, 63],
       [81, 25, 48, 35],
       [75, 79, 14, 12],
       [42, 91, 62, 41],
       [ 7, 83, 62, 58],
       [50,  1, 66, 31],
       [43, 36,  8, 95],
       [42, 27, 81, 95],
       [73, 13,  5, 25],
       [46, 61, 96, 27],
       [12, 96, 97, 50],
       [22, 44, 81, 63],
       [65,  0, 91, 90],
       [12, 74, 34, 48],
       [60, 77, 94, 72],
       [ 7, 42,  8, 62],
       [52, 54, 89, 26],
       [48, 82, 51,  3],
       [10, 15, 42, 73]])

In [143]:
print(np.argmax(predictions[19]))

4


In [ ]:
probs = model.predict(X_test)


In [147]:
predictions

array([[1.68902643e-05, 8.97302572e-03, 2.89548677e-03, 4.19625826e-02,
        8.10351670e-01, 1.35800347e-01],
       [1.42803483e-05, 4.48132958e-03, 6.02494460e-04, 5.46296798e-02,
        9.36008990e-01, 4.26325947e-03],
       [7.83943280e-04, 2.35293120e-01, 7.11715072e-02, 5.46975732e-01,
        5.79619072e-02, 8.78137425e-02],
       [3.78038891e-07, 7.66366363e-01, 3.29913193e-04, 2.13747486e-01,
        1.54992538e-02, 4.05669212e-03],
       [1.24655562e-05, 1.19096381e-04, 1.21080894e-02, 6.80591166e-02,
        8.24447751e-01, 9.52534899e-02],
       [5.42725611e-05, 2.87921692e-04, 5.61224997e-01, 3.43238637e-02,
        1.01409927e-01, 3.02699000e-01],
       [3.16483376e-04, 2.85629127e-02, 1.40342722e-02, 2.03391418e-01,
        7.35952616e-01, 1.77422892e-02],
       [3.26176905e-06, 4.01226096e-02, 6.40280321e-02, 1.04667939e-01,
        7.71102011e-01, 2.00761762e-02],
       [1.47443934e-05, 4.47248295e-03, 7.98664708e-03, 5.66514209e-02,
        6.63161576e-01, 

In [145]:
np.argmax(predictions[19])

4

In [146]:
predictions[19]

array([7.1053386e-05, 5.4309904e-03, 5.0439373e-02, 7.8934245e-02,
       6.7398441e-01, 1.9113997e-01], dtype=float32)

In [137]:
np.argmax(predictions)

112

In [148]:
np.argmax(predictions[7])

4

In [86]:
np.argmax(predictions)

0

In [87]:
y[np.argmax(predictions)]

1

In [ ]:
# Actions action = Y then +1 else 